fileList=['F_AP_FUEL_AND_WEIGHT_1_X_XX_M','F_AP_FUEL_AND_WEIGHT_2_X_XX_M','F_AP_FUEL_AND_WEIGHT_4_X_XX_M','F_AP_FUEL_AND_WEIGHT_5_X_XX_M','F_AP_FUEL_AND_WEIGHT_X_XX_M','F_AP_FUEL_AT_DEST_X_XX_M','F_AP_FUEL_FLOW_1_X_XX_M','F_AP_FUEL_FLOW_2_X_XX_M','F_AP_FUEL_LEAK_DETECTION_1_X_XX_M','F_AP_FUEL_LEAK_DETECTION_2_X_XX_M','F_AP_FUEL_LEAK_DETECTION_X_XX_M','F_AP_FUEL_WEIGHT_MANAGE_X_XX_M','F_AP_GO_AROUND_DATA_1_X_XX_M','F_AP_GO_AROUND_DATA_2_X_XX_M','F_AP_GO_AROUND_DATA_3_X_XX_M','F_AP_GO_AROUND_DATA_X_XX_M','F_AP_GROSS_WEIGHT_X_XX_M','F_AP_GROSS_WT_AND_ISA_DEV_X_XX_M','F_AP_VPP_TOC_X_KC_M','F_AP_VPP_TPA_W_CL_M','F_AP_VPP_TPA_X_XX_M','F_AP_VPP_WIND_FD_X_KC_M','F_AP_VPP_X_KC_M','F_AP_WIND_BLENDING_X_XX_M','F_AP_ZERO_FUEL_WEIGHT_X_XX_M']
srcDir=r'C:\builds\FMF RFS\6.5_Formal_Logs\\'
destDir=r'C:\builds\FMF RFS\myLogs\\'
for each in fileList:
  if(os.path.exists(srcDir+each+'-TARG.LOG')):
   if(not os.path.exists(destDir+each+'-TARG.LOG')):
    shutil.copy(srcDir+each+'-TARG.LOG',destDir+each+'-TARG.LOG')